# Generated by Django 3.2.6 on 2021-08-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_vehicle_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='tags',
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
