# Generated by Django 3.2.6 on 2021-08-15 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20210815_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='tags',
        ),
    ]
