# Generated by Django 3.2.6 on 2021-08-15 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_vehicle_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
