# Generated by Django 3.2.6 on 2021-08-15 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20210815_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('slug', models.SlugField(blank=True, default='')),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='tags',
            field=models.ManyToManyField(to='myapp.Tag'),
        ),
    ]
